services:
  p4p:
    image: ghcr.io/yaegashi/p4p-docker/p4p
    build:
      context: docker
      args:
        P4REL: r24.2
    # P4P command line options
    # https://www.perforce.com/manuals/p4sag/Content/P4SAG/chapter.proxy.html
    command: -v proxy.monitor.level=0
    # P4P Environment variables
    # https://www.perforce.com/manuals/cmdref/Content/CmdRef/envars.html
    environment:
      TZ: Asia/Tokyo
      P4DEBUG: server=1
      P4PORT: ssl:1666
      P4TARGET: ssl:target-server:1666
    ports:
      - 1666:1666
    volumes:
      - ./data:/data
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
