on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
permissions:
  packages: write
env:
  REGISTRY: ghcr.io
  IMAGE: "${{github.repository}}/p4p"
  P4REL: r24.2
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: "${{env.REGISTRY}}/${{env.IMAGE}}"
          tags: |
            type=ref,event=branch
            type=ref,event=tag
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor}} }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            P4REL=${{ env.P4REL }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ startsWith(github.ref, 'refs/tags/') && format('{0}/{1}:{2}', env.REGISTRY, env.IMAGE, env.P4REL) || '' }}
          labels: |
            ${{ steps.meta.outputs.labels }}
